# Dockerfile.backend
FROM node:18.17.0

# Instala las dependencias del sistema
RUN apt-get update; apt upgrade -y; apt-get install imagemagick -y; apt-get install graphicsmagick -y; 

# Instala las dependencias de Node.js
RUN npm install -g npm@10.2.4

