@startuml

group #FF735A 4.3.5 Delete lot by id lot 

    Farmer -> BackEnd:  DELETE delete_lot_by_id_lot/:id_lot

    BackEnd -> DB:  DELETE FROM lot_table WHERE id_lot = :id_lot

    BackEnd -> Farmer : HTTP 200 OK (Lot and related data deleted successfully)

end group

@enduml