@startuml

group #F4A020 4.3.1 Register/Update Score 

    note over Farmer
        Body {
            id_lot, 
            id_user, 
            score
        }
    endnote

    Farmer -> BackEnd: POST/PUT score_lots(Body)

    BackEnd -> DB: INSERT/UPDATE into score_lots

    DB -> BackEnd: Confirmation of insertion

    hnote over BackEnd
        Depending if the data are correct the response will be:
        201 Created (id_score_lots, id_lot, id_user, score)
        409 Conflict (score already exists)
        400 Bad Request (missing data)
        500 Internal Server Error (server error)
    endnote

    BackEnd -> Farmer: HTTP 201 Created (score registered/updated)

    note over Farmer
        Response {
            id_lot, 
            id_user, 
            score
        }
    endnote

end group

@enduml
