@startuml
    !include 5.1.fair_trade_businessman_get_farmers/5.1.0.fair_trade_businessman_top_bar_info.iuml
    !include 5.4.fair_trade_businessman_notifications/5.4.1.fair_trade_businessman_get_offers_to_buy.iuml   
    !include 5.4.fair_trade_businessman_notifications/5.4.2.fair_trade_businessman_offer_option_accept.iuml   
    !include 5.4.fair_trade_businessman_notifications/5.4.3.fair_trade_businessman_offer_option_decline.iuml   
    !include 5.4.fair_trade_businessman_notifications/5.4.4.fair_trade_businessman_get_id_make_offer.iuml   
@enduml