@startuml

    group #99FF99 5.4.1 GET offers_to_buy

        Businessman -> BackEnd: GET offers_to_buy/:id_user

        BackEnd -> DB: Select * FROM make_offer_table and users_table, countries_table, realated lot_tables.

        hnote over BackEnd
            Depending if the data are correct the response will be:
            200 OK (offers_to_buy)
            409 Conflict (user_email or user_username already exists)
            400 Bad Request (missing data)
            500 Internal Server Error (server error)
        endnote

        BackEnd -> Businessman: HTTP 200 OK (offers_to_buy_data)

        note over Businessman
            Body {
                id_make_offer
                id_offer_status
                offer_from
                offer_to
                id_lot
                offer_date
                offer_quantity
                user_name
                country_name
                user_photo_profile
                profile_name
                variety_name
            }
        endnote
    
    end group 

@enduml