INSERT INTO
	submodule_table (id_submodule, id_module, submodule_title, submodule_summary, submodule_resources, submodule_class_video, submodule_created_at, submodule_updated_at, submodule_status)
VALUES
	('1', '1', 'Prohiben el trabajo infantil', 'Descripcion prohiben el trabajo infantil. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Prohiben_el_trabajo_infantil', 'Ruta_video_submódulo_Prohiben_el_trabajo_infantil', '2024-02-01 00:00:00', '2024-02-10 00:00:00', 'true'),
	('2', '1', 'Trabajo forzado', 'Descripcion trabajo forzado. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Trabajo_forzado', 'Ruta_video_submódulo_Trabajo_forzado', '2024-02-02 00:00:00', '2024-02-11 00:00:00', 'true'),
	('3', '1', 'Condiciones laborales adecuadas', 'Descripcion condiciones laborales adecuadas. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Condiciones_laborales_adecuadas', 'Ruta_video_submódulo_Condiciones_laborales_adecuadas', '2024-02-03 00:00:00', '2024-02-12 00:00:00', 'true'),
	('4', '1', 'Prohiben el trabajo infantil', 'Descripcion prohiben el trabajo infantil. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Prohiben_el_trabajo_infantil', 'Ruta_video_submódulo_Prohiben_el_trabajo_infantil', '2024-02-04 00:00:00', '2024-02-13 00:00:00', 'true'),
	('5', '1', 'Igualdad de genero y empoderamiento de las mujeres', 'Descripcion igualdad de genero y empoderamiento de las mujeres. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Igualdad_de_genero_y_empoderamiento_de_las_mujeres', 'Ruta_video_submódulo_Igualdad_de_genero_y_empoderamiento_de_las_mujeres', '2024-02-05 00:00:00', '2024-02-14 00:00:00', 'true'),
	('6', '2', 'Precio mínimo garantizado', 'Descripcion precio mínimo garantizado. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Precio_mínimo_garantizado', 'Ruta_video_submódulo_Precio_mínimo_garantizado', '2024-02-06 00:00:00', '2024-02-15 00:00:00', 'true'),
	('7', '2', 'Prima Fair Trade', 'Descripcion prima fair trade. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Prima_Fair_Trade', 'Ruta_video_submódulo_Prima_Fair_Trade', '2024-02-07 00:00:00', '2024-02-16 00:00:00', 'true'),
	('8', '2', 'Costos de producción sostenible', 'Descripcion costos de producción sostenible. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Costos_de_producción_sostenible', 'Ruta_video_submódulo_Costos_de_producción_sostenible', '2024-02-08 00:00:00', '2024-02-17 00:00:00', 'true'),
	('9', '3', 'Transparencia', 'Descripcion transparencia. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Transparencia', 'Ruta_video_submódulo_Transparencia', '2024-02-09 00:00:00', '2024-02-18 00:00:00', 'true'),
	('10', '3', 'Practicas comerciales injustas', 'Descripcion practicas comerciales injustas. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Practicas_comerciales_injustas', 'Ruta_video_submódulo_Practicas_comerciales_injustas', '2024-02-10 00:00:00', '2024-02-19 00:00:00', 'true'),
	('11', '4', 'Agricultura sostenible ', 'Descripcion agricultura sostenible . Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Agricultura_sostenible_', 'Ruta_video_submódulo_Agricultura_sostenible_', '2024-02-11 00:00:00', '2024-02-20 00:00:00', 'true'),
	('12', '5', 'Uso de productos quimicos y pesticidas', 'Descripcion uso de productos quimicos y pesticidas. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Uso_de_productos_quimicos_y_pesticidas', 'Ruta_video_submódulo_Uso_de_productos_quimicos_y_pesticidas', '2024-02-12 00:00:00', '2024-02-21 00:00:00', 'true'),
	('13', '5', 'Gestión de residuos', 'Descripcion gestión de residuos. Lorem ipsum is a placeholder text commonly used in the printing and typesetting industry. It''s used to demonstrate the visual form of a document or a typeface without the distraction of meaningful content. ', 'ruta_recursos_submódulo_Gestión_de_residuos', 'Ruta_video_submódulo_Gestión_de_residuos', '2024-02-13 00:00:00', '2024-02-22 00:00:00', 'true');