INSERT INTO
	submodule_question_table (id_question, id_submodule, question_content, question_description)
VALUES
	('1', '1', '¿Qué prohíbe la certificación Fair Trade en relación al trabajo infantil?', 'Descripción de la pregunta ¿Qué prohíbe la certificación Fair Trade en relación al trabajo infantil?'),
	('2', '1', '¿Cuál es uno de los objetivos principales de prohibir el trabajo infantil en la certificación Fair Trade?', 'Descripción de la pregunta ¿Cuál es uno de los objetivos principales de prohibir el trabajo infantil en la certificación Fair Trade?'),
	('3', '1', '¿Qué medidas toma Fair Trade para prevenir el trabajo infantil?', 'Descripción de la pregunta ¿Qué medidas toma Fair Trade para prevenir el trabajo infantil?'),
	('4', '2', '¿Qué establece la certificación Fair Trade respecto al trabajo forzado?', 'Descripción de la pregunta ¿Qué establece la certificación Fair Trade respecto al trabajo forzado?'),
	('5', '2', '¿Cómo contribuye Fair Trade a la lucha contra el trabajo forzado?', 'Descripción de la pregunta ¿Cómo contribuye Fair Trade a la lucha contra el trabajo forzado?'),
	('6', '2', '¿Qué hace Fair Trade para verificar que no haya trabajo forzado en sus cadenas de suministro?', 'Descripción de la pregunta ¿Qué hace Fair Trade para verificar que no haya trabajo forzado en sus cadenas de suministro?'),
	('7', '3', '¿Qué promueve Fair Trade en términos de condiciones laborales?', 'Descripción de la pregunta ¿Qué promueve Fair Trade en términos de condiciones laborales?'),
	('8', '3', '¿Cuál es un principio clave de Fair Trade respecto a las condiciones laborales?', 'Descripción de la pregunta ¿Cuál es un principio clave de Fair Trade respecto a las condiciones laborales?'),
	('9', '3', '¿Cómo se asegura Fair Trade de que se mantengan condiciones laborales adecuadas?', 'Descripción de la pregunta ¿Cómo se asegura Fair Trade de que se mantengan condiciones laborales adecuadas?'),
	('10', '4', '¿Qué significa la prohibición del trabajo infantil en el marco de Fair Trade?', 'Descripción de la pregunta ¿Qué significa la prohibición del trabajo infantil en el marco de Fair Trade?'),
	('11', '4', '¿Cuál es el objetivo principal de Fair Trade al prohibir el trabajo infantil?', 'Descripción de la pregunta ¿Cuál es el objetivo principal de Fair Trade al prohibir el trabajo infantil?'),
	('12', '4', '¿Cómo asegura Fair Trade el cumplimiento de la prohibición del trabajo infantil?', 'Descripción de la pregunta ¿Cómo asegura Fair Trade el cumplimiento de la prohibición del trabajo infantil?'),
	('13', '5', '¿Qué busca Fair Trade en términos de igualdad de género?', 'Descripción de la pregunta ¿Qué busca Fair Trade en términos de igualdad de género?'),
	('14', '5', '¿Cómo apoya Fair Trade el empoderamiento de las mujeres?', 'Descripción de la pregunta ¿Cómo apoya Fair Trade el empoderamiento de las mujeres?'),
	('15', '5', '¿Qué medida promueve Fair Trade para avanzar en la igualdad de género?', 'Descripción de la pregunta ¿Qué medida promueve Fair Trade para avanzar en la igualdad de género?'),
	('16', '6', '¿Qué asegura el precio mínimo garantizado de Fair Trade para los productores?', 'Descripción de la pregunta ¿Qué asegura el precio mínimo garantizado de Fair Trade para los productores?'),
	('17', '6', '¿Cuál es el objetivo del precio mínimo garantizado por Fair Trade?', 'Descripción de la pregunta ¿Cuál es el objetivo del precio mínimo garantizado por Fair Trade?'),
	('18', '6', '¿Cómo beneficia el precio mínimo garantizado a las comunidades productoras?', 'Descripción de la pregunta ¿Cómo beneficia el precio mínimo garantizado a las comunidades productoras?'),
	('19', '7', '¿Para qué se utiliza la prima Fair Trade?', 'Descripción de la pregunta ¿Para qué se utiliza la prima Fair Trade?'),
	('20', '7', '¿Qué caracteriza a la prima Fair Trade?', 'Descripción de la pregunta ¿Qué caracteriza a la prima Fair Trade?'),
	('21', '7', '¿Quién decide cómo se gasta la prima Fair Trade?', 'Descripción de la pregunta ¿Quién decide cómo se gasta la prima Fair Trade?'),
	('22', '8', '¿Qué incluyen los costos de producción sostenible según Fair Trade?', 'Descripción de la pregunta ¿Qué incluyen los costos de producción sostenible según Fair Trade?'),
	('23', '8', '¿Cómo afecta la consideración de los costos de producción sostenible a los productores Fair Trade?', 'Descripción de la pregunta ¿Cómo afecta la consideración de los costos de producción sostenible a los productores Fair Trade?'),
	('24', '8', '¿Por qué son importantes los costos de producción sostenible en el marco de Fair Trade?', 'Descripción de la pregunta ¿Por qué son importantes los costos de producción sostenible en el marco de Fair Trade?'),
	('25', '9', '¿Qué papel juega la transparencia en Fair Trade?', 'Descripción de la pregunta ¿Qué papel juega la transparencia en Fair Trade?'),
	('26', '9', '¿Cómo beneficia la transparencia a los productores Fair Trade?', 'Descripción de la pregunta ¿Cómo beneficia la transparencia a los productores Fair Trade?'),
	('27', '9', '¿En qué manera contribuye la transparencia al éxito de Fair Trade?', 'Descripción de la pregunta ¿En qué manera contribuye la transparencia al éxito de Fair Trade?'),
	('28', '10', '¿Cómo define Fair Trade las prácticas comerciales injustas?', 'Descripción de la pregunta ¿Cómo define Fair Trade las prácticas comerciales injustas?'),
	('29', '10', '¿Qué hace Fair Trade para combatir las prácticas comerciales injustas?', 'Descripción de la pregunta ¿Qué hace Fair Trade para combatir las prácticas comerciales injustas?'),
	('30', '10', '¿Cuál es el impacto de las prácticas comerciales injustas en los productores?', 'Descripción de la pregunta ¿Cuál es el impacto de las prácticas comerciales injustas en los productores?'),
	('31', '11', '¿Qué promueve la agricultura sostenible en el contexto de Fair Trade?', 'Descripción de la pregunta ¿Qué promueve la agricultura sostenible en el contexto de Fair Trade?'),
	('32', '11', '¿Cómo beneficia la agricultura sostenible a las comunidades locales?', 'Descripción de la pregunta ¿Cómo beneficia la agricultura sostenible a las comunidades locales?'),
	('33', '11', '¿Cuál es uno de los principios de la agricultura sostenible promovida por Fair Trade?', 'Descripción de la pregunta ¿Cuál es uno de los principios de la agricultura sostenible promovida por Fair Trade?'),
	('34', '12', '¿Qué enfoque tiene Fair Trade sobre el uso de productos químicos y pesticidas?', 'Descripción de la pregunta ¿Qué enfoque tiene Fair Trade sobre el uso de productos químicos y pesticidas?'),
	('35', '12', '¿Cuál es el impacto de reducir el uso de productos químicos y pesticidas en la agricultura Fair Trade?', 'Descripción de la pregunta ¿Cuál es el impacto de reducir el uso de productos químicos y pesticidas en la agricultura Fair Trade?'),
	('36', '12', '¿Cómo se alienta a los agricultores a reducir el uso de productos químicos peligrosos en Fair Trade?', 'Descripción de la pregunta ¿Cómo se alienta a los agricultores a reducir el uso de productos químicos peligrosos en Fair Trade?'),
	('37', '13', '¿Qué prácticas de gestión de residuos promueve Fair Trade?', 'Descripción de la pregunta ¿Qué prácticas de gestión de residuos promueve Fair Trade?'),
	('38', '13', '¿Cómo afecta positivamente la gestión adecuada de residuos a las comunidades Fair Trade?', 'Descripción de la pregunta ¿Cómo afecta positivamente la gestión adecuada de residuos a las comunidades Fair Trade?'),
	('39', '13', '¿Cuál es el objetivo de las prácticas de gestión de residuos en el marco de Fair Trade?', 'Descripción de la pregunta ¿Cuál es el objetivo de las prácticas de gestión de residuos en el marco de Fair Trade?');