INSERT INTO
	submodule_answer_table (id_answer, id_question, answers_content, answers_validity)
VALUES
	('1', '1', 'Permite el trabajo infantil si es fuera del horario escolar.', 'false'),
	('2', '1', 'Prohíbe cualquier forma de trabajo infantil en sus cadenas de suministro', 'true'),
	('3', '1', 'Solo prohíbe el trabajo infantil en situaciones peligrosas o insalubres.', 'false'),
	('4', '2', 'Asegurar que los niños trabajen en un ambiente seguro.', 'false'),
	('5', '2', 'Reducir los costos de producción al evitar pagar a trabajadores adultos.', 'true'),
	('6', '2', 'Promover la educación y el bienestar de los niños evitando su explotación laboral.', 'true'),
	('7', '3', 'Ofrece educación gratuita a los niños para que prefieran estudiar en lugar de trabajar.', 'false'),
	('8', '3', 'Implementa sistemas de monitoreo y reporte para identificar y remediar casos de trabajo infantil.', 'true'),
	('9', '3', 'Obliga a las empresas a pagar multas por cada niño encontrado trabajando, sin tomar otras medidas.', 'false'),
	('10', '4', ' Permite el trabajo forzado si se justifica con necesidades económicas.', 'True'),
	('11', '4', ' Prohíbe cualquier forma de trabajo forzado o involuntario.', 'true'),
	('12', '4', ' Solo lo prohíbe para los trabajadores menores de edad.', 'false'),
	('13', '5', ' Incrementando las horas de trabajo para compensar la falta de trabajadores forzados.', 'false'),
	('14', '5', ' Permitiendo el trabajo forzado fuera de las horas pico de producción.', 'false'),
	('15', '5', ' Promoviendo la contratación voluntaria y el pago justo.', 'true'),
	('16', '6', ' Inspecciones regulares y auditorías independientes.', 'true'),
	('17', '6', ' Solo revisa las denuncias cuando se presentan quejas formales.', 'false'),
	('18', '6', ' Confía en la palabra de los productores sin necesidad de verificación.', 'false'),
	('19', '7', ' Condiciones laborales básicas que cumplan con la legislación local.', 'false'),
	('20', '7', ' Condiciones laborales adecuadas que aseguren seguridad y salud en el trabajo.', 'true'),
	('21', '7', ' Solo mejora las condiciones laborales para los trabajadores a tiempo completo.', 'false'),
	('22', '8', ' Permitir jornadas laborales extendidas sin pago de horas extras.', 'false'),
	('23', '8', ' Asegurar que todos los trabajadores tengan acceso a servicios médicos básicos.', 'true'),
	('24', '8', ' Mantener las condiciones laborales al mínimo legal para reducir costos.', 'false'),
	('25', '9', ' Requiere que los trabajadores firmen contratos que limiten sus derechos a quejarse.', 'false'),
	('26', '9', ' Mediante la formación y capacitación constante sobre derechos laborales y seguridad.', 'true'),
	('27', '9', ' Imponiendo sanciones menores a las infracciones para no afectar la producción.', 'false'),
	('28', '10', ' Los niños pueden trabajar, pero solo en tareas ligeras y no durante horas escolares.', 'false'),
	('29', '10', ' El trabajo infantil es completamente prohibido, sin excepciones.', 'true'),
	('30', '10', ' El trabajo infantil es permitido para ayudar en el negocio familiar fuera del horario escolar.', 'false'),
	('31', '11', ' Asegurar que todos los niños tengan acceso a la educación y no sean explotados a través del trabajo.', 'true'),
	('32', '11', ' Permitir que los niños aprendan el oficio de sus padres desde una edad temprana.', 'false'),
	('33', '11', ' Reducir los costos de producción al no emplear a menores de edad.', 'false'),
	('34', '12', ' A través de inspecciones esporádicas sin previo aviso.', 'false'),
	('35', '12', ' Implementando un sistema de monitoreo y verificación riguroso que incluye inspecciones regulares y la participación de la comunidad.', 'true'),
	('36', '12', ' Confiando en las declaraciones verbales de los productores sobre no emplear a menores.', 'false'),
	('37', '13', ' Garantizar que al menos un 50% de los puestos de liderazgo sean ocupados por mujeres.', 'false'),
	('38', '13', ' Promover la igualdad de oportunidades y el empoderamiento de las mujeres en todas las operaciones.', 'true'),
	('39', '13', ' Limitar la participación femenina en el trabajo agrícola a tareas específicas.', 'false'),
	('40', '14', ' Ofreciendo salarios más bajos a las mujeres para incentivar su contratación.', 'false'),
	('41', '14', ' Implementando programas de liderazgo y desarrollo profesional para mujeres.', 'true'),
	('42', '14', ' Limitando el trabajo de las mujeres a áreas tradicionalmente femeninas.', 'false'),
	('43', '15', ' Asegurando que solo los hombres tomen decisiones importantes.', 'false'),
	('44', '15', ' Facilitando acceso igualitario a la formación y recursos financieros para hombres y mujeres.', 'true'),
	('45', '15', ' Promoviendo que las mujeres trabajen exclusivamente en labores domésticas.', 'false'),
	('46', '16', ' Un precio fijo por debajo del mercado para mantener la competencia.', 'false'),
	('47', '16', ' Un precio que cubre los costos de producción sostenible, independientemente de las fluctuaciones del mercado.', 'true'),
	('48', '16', ' Un precio máximo para proteger a los consumidores de precios excesivos.', 'false'),
	('49', '17', ' Reducir los ingresos de los productores para disminuir los precios al consumidor.', 'false'),
	('50', '17', ' Proteger a los productores de la volatilidad de los precios en el mercado internacional.', 'true'),
	('51', '17', ' Incrementar los beneficios de los minoristas y distribuidores.', 'false'),
	('52', '18', ' Limitando su capacidad para invertir en mejoras de calidad.', 'false'),
	('53', '18', ' Asegurando estabilidad económica y fomentando inversiones en desarrollo comunitario.', 'true'),
	('54', '18', ' Forzando la reducción de costos a través de prácticas laborales injustas.', 'false'),
	('55', '19', ' Para pagar bonificaciones exclusivas a los altos ejecutivos de las empresas certificadas.', 'false'),
	('56', '19', ' Para financiar proyectos comunitarios y de desarrollo elegidos democráticamente por los productores.', 'true'),
	('57', '19', ' Para cubrir los gastos de marketing y publicidad de Fair Trade.', 'false'),
	('58', '20', ' Es una tarifa adicional que se aplica sobre cada producto Fair Trade vendido, destinada únicamente a mejorar la infraestructura de producción.', 'false'),
	('59', '20', ' Es una cantidad fija que se paga directamente a los consumidores como incentivo para comprar productos Fair Trade.', 'false'),
	('60', '20', ' Es un pago adicional sobre el precio de compra que se invierte en proyectos sociales, ambientales y económicos.', 'true'),
	('61', '21', ' Los directivos de Fair Trade International sin consulta alguna a los productores.', 'false'),
	('62', '21', ' Los productores y trabajadores, a través de un proceso democrático y transparente.', 'true'),
	('63', '21', ' Exclusivamente los consumidores, a través de votaciones en línea.', 'false'),
	('64', '22', ' Solamente los costos directos de materiales y mano de obra, excluyendo impactos ambientales y sociales.', 'false'),
	('65', '22', ' Los costos asociados a prácticas sostenibles, incluyendo salarios justos, condiciones laborales seguras y gestión ambiental.', 'true'),
	('66', '22', ' Únicamente los costos de certificación y etiquetado de productos como Fair Trade.', 'false'),
	('67', '23', ' Disminuye sus ganancias debido a los altos estándares requeridos sin compensación adicional.', 'false'),
	('68', '23', ' Aumenta su capacidad para invertir en mejoras continuas y sostenibilidad a largo plazo.', 'true'),
	('69', '23', ' Limita su capacidad para exportar, ya que aumenta los precios más allá de lo competitivo en el mercado global.', 'false'),
	('70', '24', ' Porque garantizan que los precios de los productos sean los más bajos posibles para los consumidores.', 'false'),
	('71', '24', ' Porque aseguran que los productores reciban una compensación que refleje el verdadero costo de una producción responsable.', 'true'),
	('72', '24', ' Porque incrementan los márgenes de beneficio para los minoristas y distribuidores de productos Fair Trade.', 'false'),
	('73', '25', ' Limita la información compartida con los consumidores para proteger las marcas.', 'false'),
	('74', '25', ' Asegura que los procesos de producción y comercio sean abiertos y accesibles para todas las partes interesadas.', 'true'),
	('75', '25', ' Se aplica solo en la fijación de precios, sin afectar otros aspectos del proceso de certificación.', 'false'),
	('76', '26', ' Les permite ocultar prácticas no sostenibles detrás de la certificación.', 'false'),
	('77', '26', ' Facilita el acceso a mercados justos y relaciones comerciales equitativas.', 'true'),
	('78', '26', ' Reduce su responsabilidad en la implementación de prácticas éticas de producción.', 'false'),
	('79', '27', ' Permitiendo a los consumidores tomar decisiones informadas y apoyar prácticas comerciales justas.', 'true'),
	('80', '27', ' Asegurando que solo la información positiva sobre Fair Trade sea compartida públicamente.', 'false'),
	('81', '27', ' Ocultando los costos reales de producción para mantener altos los precios al consumidor.', 'false'),
	('82', '28', ' Cualquier práctica que maximice las ganancias sin considerar el impacto en los productores y el medio ambiente.', 'true'),
	('83', '28', ' Solo las prácticas que resultan en salarios bajos para los trabajadores, sin considerar otros factores.', 'false'),
	('84', '28', ' Prácticas que no permiten a los productores ganar el precio mínimo garantizado.', 'false'),
	('85', '29', ' Promueve la igualdad de precios para todos los productos, independientemente de su calidad o origen.', 'false'),
	('86', '29', ' Establece relaciones directas y a largo plazo entre productores y compradores, asegurando precios justos y estabilidad.', 'true'),
	('87', '29', ' Ignora las prácticas comerciales injustas siempre que los productos cumplan con los estándares mínimos de calidad.', 'false'),
	('88', '30', ' Les permite competir en igualdad de condiciones en el mercado global.', 'false'),
	('89', '30', ' A menudo resulta en la explotación y el empobrecimiento de los productores y sus comunidades.', 'true'),
	('90', '30', ' Mejora la calidad de los productos al incentivar la competencia.', 'false'),
	('91', '31', ' El uso intensivo de pesticidas para maximizar la producción.', 'false'),
	('92', '31', ' Prácticas que protegen el medio ambiente, mejoran la calidad del suelo y conservan el agua.', 'true'),
	('93', '31', ' La conversión de tierras agrícolas en áreas industriales para aumentar la eficiencia.', 'false'),
	('94', '32', ' Aumentando la dependencia en tecnologías extranjeras y pesticidas.', 'false'),
	('95', '32', ' Mejorando la seguridad alimentaria y promoviendo la biodiversidad.', 'true'),
	('96', '32', ' Centrándose únicamente en cultivos de exportación para aumentar los ingresos.', 'false'),
	('97', '33', ' El monocultivo extensivo para la exportación.', 'false'),
	('98', '33', ' La rotación de cultivos y el uso de abonos orgánicos para mantener la salud del suelo.', 'true'),
	('99', '33', ' La maximización del uso de terrenos agrícolas sin considerar las consecuencias ambientales.', 'false'),
	('100', '34', ' Promueve el uso libre e ilimitado de pesticidas para asegurar altos rendimientos.', 'false'),
	('101', '34', ' Fomenta prácticas agrícolas que minimicen el uso de productos químicos dañinos y promuevan alternativas más seguras.', 'true'),
	('102', '34', ' Prohíbe cualquier tipo de producto químico en la agricultura, incluyendo fertilizantes orgánicos.', 'false'),
	('103', '35', ' Disminuye la productividad y aumenta los costos de producción significativamente.', 'false'),
	('104', '35', ' Mejora la salud del suelo y la biodiversidad, beneficiando a largo plazo a la producción agrícola.', 'true'),
	('105', '35', ' Aumenta la dependencia en mano de obra, haciéndola menos sostenible económicamente.', 'false'),
	('106', '36', ' Ofreciendo premios monetarios a los que usen más pesticidas para proteger sus cultivos.', 'false'),
	('107', '36', ' A través de capacitaciones sobre prácticas agrícolas sostenibles y el uso de alternativas orgánicas.', 'true'),
	('108', '36', ' Limitando la certificación Fair Trade a productos orgánicos exclusivamente.', 'false'),
	('109', '37', ' La eliminación de residuos en vertederos como método principal.', 'false'),
	('110', '37', ' La reducción, reutilización y reciclaje de residuos para minimizar el impacto ambiental.', 'true'),
	('111', '37', ' La quema al aire libre de residuos agrícolas y plásticos para reducir volumen.', 'false'),
	('112', '38', ' Generando ingresos adicionales a través de la venta de residuos reciclables.', 'false'),
	('113', '38', ' Reduciendo la contaminación y mejorando la salud y calidad de vida de la comunidad.', 'true'),
	('114', '38', ' Aumentando la cantidad de residuos producidos para fomentar la innovación en gestión de residuos.', 'false'),
	('115', '39', ' Incrementar los costos de producción para los agricultores y productores.', 'false'),
	('116', '39', ' Contribuir a la sostenibilidad ambiental y al bienestar de las comunidades.', 'true'),
	('117', '39', ' Cumplir con regulaciones locales sin buscar una mejora real en la gestión de residuos.', 'false');