@startuml
    !include 5.1.businessman_get_farmers/5.1.0.businessman_top_bar_info.iuml
    !include 5.2.businessman_edit_profile/5.2.1.businessman_get_profile.iuml
    !include 5.3.businessman_get_farmer_lots/5.3.1.businessman_get_lots_by_user.iuml
@enduml